services:
  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
    - .:/usr/src/app

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "5050:80"

volumes: 
    data: {}